### ISSUE TITLE
Site Doesn't populate anything

### ISSUE THREAD

**Issue by Firminator** [Derekt2/CISA-Log4J-DB-Frontend#2]
![Screenshot from 2021-12-21 09-46-24](https://user-images.githubusercontent.com/12078737/146949006-935074ee-c5d4-48e1-bc8b-b8590edfe2eb.png)

Speculating here that it might be because some of the source table column headers were changed yesterday. It's now
```
| Vendor | Product | Version(s) | Status | Update Available | Vendor Link | Notes | Other References | Last Updated |
```

https://github.com/Derekt2/CISA-Log4J-DB-Frontend/blob/e86a2045ba2ed5c03084f92945b2c85e00490e64/src/App.vue#L82-L102

**Comment by Derekt2** [comment]
Thanks for the heads up! Fixed it for now. 

It seems someone modified the delimiter I was using to parse the data. Since there isn't a clear start point for the data (the field names or data or structure could change), it's a bit brittle. Time will tell whether this method will remain viable as there's already issues and PRs trying to split the readme into several different files for ease of contributing. 

Hopefully they'll migrate to a database or even CSV.
